discord:
  webhook_url: "https://discord.com/api/webhooks/1514287474501881907/zR8JbvC9zZnGttbfZU9fePdqMNTiypBbDgiJ4Wdxk8j_S4xx7kk_S7BnnIA9O6onPprd"

symbols: ["BTC/USDT", "SOL/USDT"]

alerts:
  trend_reversal: true
  strong_signal_threshold: 0.75
  report_schedule:
    - "08:00"
    - "12:00"
    - "20:00"
